"""Provider abstraction and response caching for LLM calls.

No provider is configured and no call has ever been made. This layer exists so that when a key
arrives, swapping providers is a constructor argument rather than a rewrite — and so that
different models can be benchmarked against each other on identical inputs later.

**Caching is not an optimisation here, it is an evaluation requirement.** An evaluation that
re-queries a model on every run is neither reproducible nor free: the same input can yield a
different reply, and a reviewer re-running the harness pays for it again. Responses are keyed
by (provider, model, prompt-version, prompt-hash) so a prompt edit correctly misses the cache
instead of silently returning a reply generated by different instructions.

``NullProvider`` is the default. It raises a message naming exactly what to configure rather
than returning a plausible-looking string, because a silent fallback would let an unconfigured
system produce output that looks like a model wrote it.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path


class LLMNotConfiguredError(RuntimeError):
    """Raised when generation is attempted with no provider configured."""


@dataclass(frozen=True, slots=True)
class LLMResponse:
    text: str
    provider: str
    model: str
    from_cache: bool = False
    prompt_version: str = "v1"


class LLMProvider:
    """Interface every provider implements."""

    name: str = "base"
    model: str = "none"

    def complete(self, prompt: str, *, max_tokens: int = 400, temperature: float = 0.0) -> str:
        raise NotImplementedError


class NullProvider(LLMProvider):
    """Default provider: refuses loudly instead of inventing a reply."""

    name = "null"
    model = "none"

    def complete(self, prompt: str, *, max_tokens: int = 400, temperature: float = 0.0) -> str:
        raise LLMNotConfiguredError(
            "No LLM provider is configured. The agent runs end-to-end without one using the "
            "deterministic evidence-grounded generator. To enable LLM generation, set an API "
            "key and pass a configured provider to ReplyAgent(generator=...). "
            "See docs/AGENT.md for provider options and cost estimates."
        )


class AnthropicProvider(LLMProvider):  # pragma: no cover - requires a key to exercise
    """Anthropic Claude. Untested here: no key has ever been configured."""

    name = "anthropic"

    def __init__(self, model: str = "claude-sonnet-5", api_key: str | None = None) -> None:
        self.model = model
        self._api_key = api_key or os.getenv("ANTHROPIC_API_KEY")
        if not self._api_key:
            raise LLMNotConfiguredError("ANTHROPIC_API_KEY is not set")

    def complete(self, prompt: str, *, max_tokens: int = 400, temperature: float = 0.0) -> str:
        from anthropic import Anthropic

        message = Anthropic(api_key=self._api_key).messages.create(
            model=self.model,
            max_tokens=max_tokens,
            temperature=temperature,
            messages=[{"role": "user", "content": prompt}],
        )
        return "".join(block.text for block in message.content if block.type == "text")


class CachedProvider(LLMProvider):
    """Wraps a provider with an on-disk cache keyed by provider, model, prompt and version."""

    def __init__(
        self,
        provider: LLMProvider,
        cache_dir: Path,
        prompt_version: str = "v1",
    ) -> None:
        self.provider = provider
        self.name = provider.name
        self.model = provider.model
        self.prompt_version = prompt_version
        self.cache_dir = cache_dir
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.hits = 0
        self.misses = 0

    def _key(self, prompt: str) -> str:
        payload = f"{self.provider.name}|{self.provider.model}|{self.prompt_version}|{prompt}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    def complete(self, prompt: str, *, max_tokens: int = 400, temperature: float = 0.0) -> str:
        path = self.cache_dir / f"{self._key(prompt)}.json"
        if path.exists():
            self.hits += 1
            return json.loads(path.read_text(encoding="utf-8"))["response"]

        self.misses += 1
        response = self.provider.complete(
            prompt, max_tokens=max_tokens, temperature=temperature
        )
        path.write_text(
            json.dumps(
                {
                    "provider": self.provider.name,
                    "model": self.provider.model,
                    "prompt_version": self.prompt_version,
                    "prompt": prompt,
                    "response": response,
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return response
