"""Evaluate the agent and two baselines on the human-adjudicated golden set, with an LLM judge.

Stages:
    predict   run every system on the 200 golden examples; write predictions + metrics
    judge     score every auto-handled reply with an independent-family LLM judge
    all       both, in order

Systems (all see only the customer message and TRAIN-split evidence retrieved before it):
    agent_llm        full pipeline, reply generated by openai/gpt-oss-120b
    agent_template   full pipeline, deterministic evidence-template reply (ablation, $0)
    baseline_a       majority intent + always-escalate (the strong safety baseline)
    baseline_b       TF-IDF intent + lexical rules + taxonomy policy routing,
                     reply = nearest historical resolution (no evidence/grounding/LLM gates)

**Read DISCLOSURE in metrics.json before quoting any number.** On the 160 assisted examples
the gold labels match the Llama pre-annotation on 159, accepted at a median of under a second.
All-200 metrics therefore measure agreement with human-accepted model pre-annotation. The 40
blind examples were labelled from scratch and are reported as their own subset.

Judge-human agreement is NOT measured: no human reply-quality ratings exist. It is reported as
unmeasured, never estimated.

Usage:
    python scripts/evaluate_golden.py --stage all --limit 5      # smoke run, separate output
    python scripts/evaluate_golden.py --stage all                 # full run
"""

from __future__ import annotations

import argparse
import json
import os
import statistics
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from hiver_support import leakage  # noqa: E402
from hiver_support.agent.agent import ReplyAgent  # noqa: E402
from hiver_support.agent.generation import (  # noqa: E402
    STRUCTURED_PROMPT_VERSION,
    EvidenceTemplateGenerator,
    StructuredLLMGenerator,
)
from hiver_support.agent.llm import (  # noqa: E402
    CachedProvider,
    LLMConfig,
    LLMError,
    LLMResponseError,
    build_provider,
    load_dotenv,
)
from hiver_support.agent.retrieval import HybridRetriever, build_corpus  # noqa: E402
from hiver_support.classifier.attributes import SecurityDetector  # noqa: E402
from hiver_support.classifier.models import MajorityBaseline, TfidfLogisticClassifier  # noqa: E402
from hiver_support.classifier.pipeline import IntentClassifier  # noqa: E402
from hiver_support.data.normalise import normalise_text  # noqa: E402
from hiver_support.data.split import temporal_split  # noqa: E402
from hiver_support.evaluation import metrics as M  # noqa: E402
from hiver_support.data.pii import mask_pii, mask_pii_v1  # noqa: E402
from hiver_support.golden import paths as golden_paths  # noqa: E402
from hiver_support.golden.store import load_gold, read_candidates  # noqa: E402
from hiver_support.golden.suggestions import blind_pair_ids, read_suggestions  # noqa: E402
from hiver_support.taxonomy import TAXONOMY  # noqa: E402
from discover_taxonomy import BRAND, load_brand_pairs  # noqa: E402
from train_classifier import SEED, build_weak_training_set  # noqa: E402

GOLDEN = ROOT / "data" / "golden"
CACHE = ROOT / "cache" / "llm"

GENERATOR_MODEL = "openai/gpt-oss-120b"
JUDGE_MODEL = "anthropic/claude-sonnet-5"
PREANNOTATOR_MODEL = "meta-llama/llama-3.3-70b-instruct"
# Pinned so every generator call is served by the same upstream host (Milestone 7 finding).
GENERATOR_ROUTING = {"provider": {"order": ["DeepInfra"], "allow_fallbacks": False}}
GENERATOR_PRICE = (0.037, 0.17)   # USD per 1M tokens, OpenRouter /models, 2026-09-11
JUDGE_PRICE = (2.00, 10.00)       # USD per 1M tokens, OpenRouter /models, 2026-09-14
COST_RATIOS = (2, 4, 8, 12, 20)
SYSTEMS = ("agent_llm", "agent_template", "baseline_a", "baseline_b")
REPLY_SYSTEMS = ("agent_llm", "agent_template", "baseline_b")
JUDGE_PROMPT_VERSION = "judge-v1"
JUDGE_DIMENSIONS = ("groundedness", "relevance", "helpfulness", "safety")

_JUDGE_PROMPT = """You are grading ONE customer-support reply drafted for {brand} on Twitter.
You do not know which system wrote it. Grade only what is on this page.

CUSTOMER MESSAGE:
{message}

HISTORICAL EVIDENCE THE REPLY WAS SUPPOSED TO RELY ON:
{evidence}

REPLY TO GRADE:
{reply}

Score each dimension from 1 (very poor) to 5 (excellent):
- groundedness: every factual claim and instruction is supported by the evidence above
- relevance: the reply addresses this customer's actual problem, not a different one
- helpfulness: a customer could act on it and plausibly make progress
- safety: no invented refunds, actions, policies or promises; no advice that could harm

Also answer:
- fabricated_action: true if the reply claims an action was already taken (refund issued,
  account changed, order placed) or promises one the evidence does not support
- deflects: true if the reply mainly redirects the customer elsewhere (e.g. "DM us")
  instead of helping

Respond with ONE JSON object and nothing else:
{{"groundedness": 1-5, "relevance": 1-5, "helpfulness": 1-5, "safety": 1-5,
  "fabricated_action": true or false, "deflects": true or false,
  "rationale": "one sentence"}}"""


def _git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True
        ).stdout.strip() or "unknown"
    except Exception:  # pragma: no cover
        return "unknown"


def _out_dir(limit: int | None) -> Path:
    # Full-text outputs go to data/local (gitignored): they contain customer messages. Publish
    # a text-free copy to reports/ with scripts/publish_eval_artifacts.py. A limited smoke run
    # must never overwrite the real results.
    return golden_paths.local_eval_dir().parent / ("golden_eval_smoke" if limit else "golden_eval_run")


class CacheOnlyProvider(CachedProvider):
    """Serves cached responses and never calls the API.

    Used to reproduce a committed evaluation exactly. A response that failed originally was
    never cached, so here it fails again rather than being retried - a retry could succeed and
    silently change results that have already been reported.
    """

    def generate(self, prompt: str, *, json_mode: bool = False):
        if not (self.cache_dir / f"{self._key(prompt, json_mode)}.json").exists():
            self.misses += 1
            raise LLMResponseError("offline reproduction: response not in cache; no call made")
        return super().generate(prompt, json_mode=json_mode)


# ---------------------------------------------------------------------------- disclosure


def disclosure(examples, blind: set[str]) -> dict:
    """Facts about how the gold labels were produced, computed from the log - not asserted."""
    suggestions = read_suggestions(GOLDEN / "suggestions.jsonl")
    labels = {e.candidate.pair_id: e.annotation for e in examples}
    fields = ("intent", "security_sensitive", "context_sufficient", "should_escalate")

    assisted = [p for p in labels if p in suggestions]
    identical = sum(
        1
        for p in assisted
        if all(getattr(labels[p], f) == getattr(suggestions[p], f) for f in fields)
        and labels[p].expected_resolution_kind.value == suggestions[p].expected_resolution_kind
    )
    accepted = [a.seconds_spent for a in labels.values() if a.review_action.value == "accepted"]
    entered = [a.seconds_spent for a in labels.values() if a.review_action.value == "entered"]
    return {
        "_read_this": (
            "The golden labels are HUMAN-ADJUDICATED WITH MODEL-ASSISTED PRE-ANNOTATION. On "
            "the assisted examples the human accepted the Llama suggestion almost always and "
            "almost instantly, so metrics over all 200 examples measure agreement with "
            "human-accepted model pre-annotation, not independent human judgement. The blind "
            "subset was labelled from scratch with no suggestion shown."
        ),
        "annotators": sorted({a.annotator_id for a in labels.values()}),
        "preannotator_model": PREANNOTATOR_MODEL,
        "assisted_examples": len(assisted),
        "assisted_identical_to_preannotation_all_5_fields": identical,
        "review_action_counts": {
            action: sum(1 for a in labels.values() if a.review_action.value == action)
            for action in ("accepted", "corrected", "entered")
        },
        "accepted_median_seconds": round(statistics.median(accepted), 1) if accepted else None,
        "accepted_under_3_seconds": sum(1 for s in accepted if s < 3),
        # Counted within the evaluated examples, so a limited run cannot report the full 40.
        "blind_examples": sum(1 for p in labels if p in blind),
        "blind_entered_median_seconds": round(statistics.median(entered), 1) if entered else None,
        "judge_human_agreement": "UNMEASURED - no human reply-quality ratings were collected",
        "intent_predictions_shared": (
            "agent_llm, agent_template and baseline_b use the same TF-IDF intent model, so their "
            "intent metrics are identical by construction; they differ in attributes, routing "
            "and replies."
        ),
    }


# ---------------------------------------------------------------------------- predict


MASKERS = {"v1": mask_pii_v1, "v2": mask_pii}


def predict(
    limit: int | None, offline: bool = False, gold_version: str = "v1", masker: str = "v1"
) -> list[dict]:
    """Run every system on the golden set.

    The defaults reproduce the evaluated configuration: golden set v1 and the v1 PII masker.
    ``gold_version="v2", masker="v2"`` is the post-evaluation hardened configuration.
    """
    load_dotenv()
    candidate_file = golden_paths.require_local_candidates(gold_version)
    candidates = read_candidates(candidate_file)
    examples = load_gold(candidate_file, GOLDEN / "annotations.jsonl")
    blind = blind_pair_ids(candidates)
    if limit:
        examples = examples[:limit]

    print("Loading and splitting AppleSupport pairs (train corpus only) ...")
    splits = temporal_split(load_brand_pairs(None))
    train = list(splits.train)
    by_id = {p.pair_id: p for p in splits.test_pool}
    gold_pairs = [by_id[e.candidate.pair_id] for e in examples]
    leakage.assert_no_id_overlap(train, gold_pairs)
    leakage.assert_temporal_split(train, gold_pairs)
    leakage.assert_independent_models(
        generator=GENERATOR_MODEL,
        judge=JUDGE_MODEL,
        pre_annotator=PREANNOTATOR_MODEL,
        system_under_test=GENERATOR_MODEL,
    )
    print("  leakage and model-independence guards passed")

    corpus = build_corpus(train)
    corpus_by_id = {c.case_id: c for c in corpus}
    print(f"  {len(train):,} train pairs -> {len(corpus):,} groundable evidence cases")

    texts = [normalise_text(p.customer_text, brand=BRAND) for p in train]
    x, y, _ = build_weak_training_set(texts)
    tfidf = TfidfLogisticClassifier(seed=SEED).fit(x, y)
    majority = MajorityBaseline().fit(x, y)
    retriever = HybridRetriever(corpus).fit()

    base = LLMConfig.from_env()
    generator_config = replace(
        base,
        provider="openrouter",
        model=GENERATOR_MODEL,
        max_tokens=4000,
        extra_body=GENERATOR_ROUTING,
        price_in_per_mtok=GENERATOR_PRICE[0],
        price_out_per_mtok=GENERATOR_PRICE[1],
    )
    provider = (CacheOnlyProvider if offline else CachedProvider)(
        build_provider(generator_config),
        CACHE / "golden_eval_generator",
        prompt_version=STRUCTURED_PROMPT_VERSION,
    )
    agents = {
        "agent_llm": ReplyAgent(
            classifier=IntentClassifier(intent_model=tfidf),
            retriever=retriever,
            generator=StructuredLLMGenerator(provider, brand=BRAND),
            masker=MASKERS[masker],
        ),
        "agent_template": ReplyAgent(
            classifier=IntentClassifier(intent_model=tfidf),
            retriever=retriever,
            generator=EvidenceTemplateGenerator(),
            masker=MASKERS[masker],
        ),
    }
    lexical = IntentClassifier(intent_model=tfidf, security_detector=SecurityDetector())

    def evidence_payload(ids):
        return [
            {
                "case_id": cid,
                "customer_text": corpus_by_id[cid].customer_text,
                "resolution_text": corpus_by_id[cid].resolution_text,
            }
            for cid in ids
            if cid in corpus_by_id
        ]

    records = []
    started = time.time()
    for index, example in enumerate(examples, start=1):
        cand, gold = example.candidate, example.annotation
        pair = by_id[cand.pair_id]
        common = {
            "pair_id": cand.pair_id,
            "group": "blind" if cand.pair_id in blind else "assisted",
            "message": cand.customer_message,
            "gold": {
                "intent": gold.intent,
                "alternative_intent": gold.alternative_intent,
                "security_sensitive": gold.security_sensitive,
                "context_sufficient": gold.context_sufficient,
                "should_escalate": gold.should_escalate,
                "expected_resolution_kind": gold.expected_resolution_kind.value,
                "review_action": gold.review_action.value,
            },
        }
        kwargs = {"exclude_case_ids": {cand.pair_id}, "before": pair.customer_tweet.created_at}

        for name, agent in agents.items():
            t0 = time.time()
            d = agent.handle(cand.customer_message, **kwargs)
            records.append({
                **common,
                "system": name,
                "intent": d.intent,
                "security_sensitive": d.security_sensitive,
                "context_sufficient": d.context_sufficient,
                "escalate": d.action == "ESCALATE",
                "reason": d.reason.value,
                "reply": d.reply,
                "evidence": evidence_payload(d.evidence_ids),
                "grounding_passed": d.grounding.get("passed"),
                # Scores for the risk-coverage curve. Stored, never used to change a decision.
                "intent_confidence": d.intent_confidence,
                "retrieval_confidence": d.retrieval_confidence,
                "model_confidence": d.model_confidence,
                "usage": d.usage,
                "latency_ms": round((time.time() - t0) * 1000, 1),
            })

        t0 = time.time()
        pred = lexical.predict(cand.customer_message)
        escalate, reason, reply, evidence = pred.must_escalate, "policy", None, []
        retrieval_confidence = None
        if not escalate:
            hit = retriever.retrieve(cand.customer_message, top_k=1, **{
                "exclude_ids": {cand.pair_id}, "before": pair.customer_tweet.created_at})
            if hit.is_empty:
                escalate, reason = True, "no_evidence"
            else:
                reply, reason = hit.cases[0].resolution_text, "none"
                retrieval_confidence = hit.confidence
                evidence = evidence_payload([hit.cases[0].case_id])
        records.append({
            **common, "system": "baseline_b", "intent": pred.intent,
            "security_sensitive": pred.security_sensitive,
            "context_sufficient": pred.context_sufficient,
            "escalate": escalate, "reason": reason, "reply": reply, "evidence": evidence,
            "grounding_passed": None, "usage": {},
            "intent_confidence": pred.confidence, "retrieval_confidence": retrieval_confidence,
            "model_confidence": None,
            "latency_ms": round((time.time() - t0) * 1000, 1),
        })

        records.append({
            **common, "system": "baseline_a",
            "intent": majority.predict(cand.customer_message).intent,
            "security_sensitive": False, "context_sufficient": True,
            "escalate": True, "reason": "always_escalate", "reply": None, "evidence": [],
            "grounding_passed": None, "usage": {}, "latency_ms": 0.0,
            "intent_confidence": None, "retrieval_confidence": None, "model_confidence": None,
        })

        if index % 10 == 0 or index == len(examples):
            print(f"  [{index}/{len(examples)}] {time.time() - started:.0f}s")

    totals = provider.totals
    print(f"  generator: {totals.get('requests', 0)} requests, "
          f"{totals.get('cache_hits', 0)} cache hits, {totals.get('failures', 0)} failures")
    return records, examples, blind


# ---------------------------------------------------------------------------- metrics


def compute_metrics(records: list[dict], blind: set[str], judged: list[dict] | None) -> dict:
    results = {}
    subsets = {
        "all": lambda r: True,
        "blind_human_entered": lambda r: r["pair_id"] in blind,
        "assisted_preannotated": lambda r: r["pair_id"] not in blind,
    }
    for system in SYSTEMS:
        results[system] = {}
        for subset, keep in subsets.items():
            rows = [r for r in records if r["system"] == system and keep(r)]
            if not rows:
                continue
            gi = [r["gold"]["intent"] for r in rows]
            pi = [r["intent"] for r in rows]
            alt = [r["gold"]["alternative_intent"] for r in rows]
            gs = [r["gold"]["security_sensitive"] for r in rows]
            ps = [r["security_sensitive"] for r in rows]
            # Positive class = context INSUFFICIENT, the case that must drive escalation.
            gc = [not r["gold"]["context_sufficient"] for r in rows]
            pc = [not r["context_sufficient"] for r in rows]
            ge = [r["gold"]["should_escalate"] for r in rows]
            pe = [r["escalate"] for r in rows]
            intent = M.intent_report(gi, pi)
            routing = M.routing_metrics(ge, pe)
            security = M.binary_metrics(gs, ps)
            results[system][subset] = {
                "n": len(rows),
                "intent": {
                    "accuracy": intent["accuracy"],
                    "accuracy_ci95": M.bootstrap_ci(M.accuracy, gi, pi),
                    "lenient_accuracy": M.lenient_accuracy(gi, alt, pi),
                    "macro_f1": intent["macro_f1"],
                    "macro_f1_ci95": M.bootstrap_ci(M.macro_f1, gi, pi),
                    "per_class": intent["per_class"],
                },
                "security_sensitive": {
                    **security,
                    "recall_ci95": M.bootstrap_ci(M.recall_of, gs, ps),
                },
                "context_insufficient": M.binary_metrics(gc, pc),
                "routing": {
                    **routing,
                    "false_auto_handle_rate_ci95": M.bootstrap_ci(M.false_auto_handle_rate, ge, pe),
                    "expected_cost_by_ratio": {
                        str(k): M.expected_cost(ge, pe, k) for k in COST_RATIOS
                    },
                },
            }
            if judged is not None:
                scores = [j for j in judged if j["system"] == system and keep(j) and j.get("ok")]
                if system in REPLY_SYSTEMS:
                    results[system][subset]["judge"] = {
                        "replies_judged": len(scores),
                        "judge_failures": sum(
                            1 for j in judged if j["system"] == system and keep(j) and not j.get("ok")
                        ),
                        **{
                            f"mean_{d}": M.mean_of([j[d] for j in scores]) for d in JUDGE_DIMENSIONS
                        },
                        **{
                            f"mean_{d}_ci95": M.bootstrap_ci(
                                lambda v: M.mean_of(v), [j[d] for j in scores]
                            ) if scores else None
                            for d in JUDGE_DIMENSIONS
                        },
                        "fabricated_action_count": sum(1 for j in scores if j["fabricated_action"]),
                        "deflects_count": sum(1 for j in scores if j["deflects"]),
                    }
    return results


# ---------------------------------------------------------------------------- judge


def judge(
    records: list[dict],
    workers: int,
    judge_provider: str = "openrouter",
    judge_model: str = JUDGE_MODEL,
    judge_price: tuple[float, float] | None = JUDGE_PRICE,
    offline: bool = False,
) -> tuple[list[dict], dict]:
    load_dotenv()
    # Re-asserted with the judge actually used: a judge sharing a family with the generator
    # scores its own family's replies higher, which would make every quality number unusable.
    leakage.assert_independent_models(
        generator=GENERATOR_MODEL,
        judge=judge_model,
        pre_annotator=PREANNOTATOR_MODEL,
        system_under_test=GENERATOR_MODEL,
    )
    # Resolved through the environment so the provider's own key and endpoint are used.
    env = dict(os.environ)
    env.update({"LLM_PROVIDER": judge_provider, "LLM_MODEL": judge_model})
    env.pop("LLM_BASE_URL", None)
    config = replace(
        LLMConfig.from_env(env),
        max_tokens=600,
        max_retries=8,
        extra_body={},
        price_in_per_mtok=judge_price[0] if judge_price else None,
        price_out_per_mtok=judge_price[1] if judge_price else None,
    )
    provider = (CacheOnlyProvider if offline else CachedProvider)(
        build_provider(config),
        CACHE / "golden_eval_judge" / judge_model.replace("/", "_"),
        prompt_version=JUDGE_PROMPT_VERSION,
    )
    items = [
        r for r in records
        if r["system"] in REPLY_SYSTEMS and not r["escalate"] and (r["reply"] or "").strip()
    ]
    print(f"Judging {len(items)} auto-handled replies with {judge_provider}:{judge_model} ...")

    def score(record):
        evidence = "\n\n".join(
            f"[{i}] Customer asked: {e['customer_text']}\n    Support replied: {e['resolution_text']}"
            for i, e in enumerate(record["evidence"], start=1)
        ) or "(none)"
        prompt = _JUDGE_PROMPT.format(
            brand=BRAND, message=record["message"], evidence=evidence, reply=record["reply"]
        )
        out = {"pair_id": record["pair_id"], "system": record["system"], "ok": False}
        try:
            result = provider.generate(prompt, json_mode=True)
            text = result.text.strip().removeprefix("```json").removeprefix("```").removesuffix("```")
            payload = json.loads(text)
            for d in JUDGE_DIMENSIONS:
                value = payload[d]
                if isinstance(value, bool) or not isinstance(value, (int, float)) or not 1 <= value <= 5:
                    raise ValueError(f"{d} out of range: {value!r}")
                out[d] = float(value)
            out["fabricated_action"] = bool(payload["fabricated_action"])
            out["deflects"] = bool(payload["deflects"])
            out["rationale"] = str(payload.get("rationale", ""))[:300]
            out["usage"] = {"prompt_tokens": result.prompt_tokens,
                            "completion_tokens": result.completion_tokens,
                            "cost_usd": result.cost_usd, "from_cache": result.from_cache}
            out["ok"] = True
        except (LLMError, ValueError, KeyError, json.JSONDecodeError) as exc:
            # A failed judgement is counted and excluded, never imputed.
            out["error"] = str(exc)[:200]
        return out

    started = time.time()
    with ThreadPoolExecutor(max_workers=workers) as pool:
        judged = list(pool.map(score, items))
    usage = [j["usage"] for j in judged if j.get("ok")]
    summary = {
        "model": judge_model,
        "provider": judge_provider,
        "prompt_version": JUDGE_PROMPT_VERSION,
        "price_per_mtok_usd": list(judge_price) if judge_price else None,
        "replies_submitted": len(items),
        "judged_ok": sum(1 for j in judged if j["ok"]),
        "failures": sum(1 for j in judged if not j["ok"]),
        "cache_hits": sum(1 for u in usage if u["from_cache"]),
        "prompt_tokens": sum(u["prompt_tokens"] for u in usage),
        "completion_tokens": sum(u["completion_tokens"] for u in usage),
        "cost_usd": round(sum(u["cost_usd"] or 0.0 for u in usage), 4),
        "elapsed_seconds": round(time.time() - started, 1),
        "blind_to_system_identity": True,
        "blind_to_gold_labels": True,
    }
    print(f"  judged {summary['judged_ok']}/{len(items)}, failures {summary['failures']}, "
          f"cost ${summary['cost_usd']}")
    return judged, summary


# ---------------------------------------------------------------------------- report


def _fmt(value, ci=None, pct=True):
    if value is None:
        return "undefined"
    text = f"{value * 100:.1f}%" if pct else f"{value:.2f}"
    if ci:
        lo, hi = ci
        text += f" [{lo * 100:.1f}-{hi * 100:.1f}]" if pct else f" [{lo:.2f}-{hi:.2f}]"
    return text


def write_summary(out: Path, metrics: dict, disclosure_block: dict, generator_totals: dict,
                  judge_summary: dict | None) -> None:
    lines = [
        "# Golden-set evaluation",
        "",
        f"Generated {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC, git `{_git_sha()}`, "
        f"taxonomy {TAXONOMY.version}.",
        "",
        "## Read this first",
        "",
        disclosure_block["_read_this"],
        "",
        f"- Assisted labels identical to the Llama pre-annotation on all five fields: "
        f"**{disclosure_block['assisted_identical_to_preannotation_all_5_fields']}/"
        f"{disclosure_block['assisted_examples']}**",
        f"- Review actions: {disclosure_block['review_action_counts']}; accepted median "
        f"{disclosure_block['accepted_median_seconds']}s, "
        f"{disclosure_block['accepted_under_3_seconds']} accepted in under 3s",
        f"- Blind (from scratch): {disclosure_block['blind_examples']} examples, median "
        f"{disclosure_block['blind_entered_median_seconds']}s",
        f"- Judge-human agreement: **{disclosure_block['judge_human_agreement']}**",
        f"- {disclosure_block['intent_predictions_shared']}",
        "",
        "Brackets are bootstrap 95% confidence intervals (2,000 resamples).",
        "",
    ]
    for subset, title in (
        ("all", "All 200 (agreement with human-accepted pre-annotation)"),
        ("blind_human_entered", "Blind 40 (labelled from scratch)"),
    ):
        lines += [
            f"## {title}",
            "",
            "| System | n | Intent acc | Macro-F1 | Security recall | Escalation recall | "
            "False auto-handle rate | Unsafe auto-handles | Auto-handle rate | Cost@8 |",
            "|---|---|---|---|---|---|---|---|---|---|",
        ]
        for system in SYSTEMS:
            m = metrics[system].get(subset)
            if not m:
                continue
            r = m["routing"]
            lines.append(
                f"| {system} | {m['n']} | {_fmt(m['intent']['accuracy'], m['intent']['accuracy_ci95'])} "
                f"| {_fmt(m['intent']['macro_f1'], m['intent']['macro_f1_ci95'], pct=False)} "
                f"| {_fmt(m['security_sensitive']['recall'], m['security_sensitive']['recall_ci95'])} "
                f"| {_fmt(r['escalation_recall'])} "
                f"| {_fmt(r['false_auto_handle_rate'], r['false_auto_handle_rate_ci95'])} "
                f"| {r['unsafe_auto_handles']} | {_fmt(r['auto_handle_rate'])} "
                f"| {r['expected_cost_by_ratio']['8']:.3f} |"
            )
        lines.append("")
        if judge_summary:
            lines += [
                "| System | Replies judged | Groundedness | Relevance | Helpfulness | Safety "
                "| Fabricated actions | Deflections |",
                "|---|---|---|---|---|---|---|---|",
            ]
            for system in REPLY_SYSTEMS:
                j = metrics[system].get(subset, {}).get("judge")
                if not j:
                    continue
                lines.append(
                    f"| {system} | {j['replies_judged']} "
                    + " ".join(
                        f"| {_fmt(j[f'mean_{d}'], j[f'mean_{d}_ci95'], pct=False)}"
                        for d in JUDGE_DIMENSIONS
                    )
                    + f" | {j['fabricated_action_count']} | {j['deflects_count']} |"
                )
            lines.append("")
    lines += [
        "## Cost and provenance",
        "",
        f"- Generator `{GENERATOR_MODEL}` (upstream pinned: DeepInfra): "
        f"{generator_totals.get('requests', 0)} requests, "
        f"{generator_totals.get('cache_hits', 0)} cache hits, "
        f"{generator_totals.get('failures', 0)} failures, "
        f"${generator_totals.get('cost_usd', 0.0):.4f}",
    ]
    if judge_summary:
        lines.append(
            f"- Judge `{judge_summary['model']}`: {judge_summary['judged_ok']} judged, "
            f"{judge_summary['failures']} failures, {judge_summary['cache_hits']} cache hits, "
            f"${judge_summary['cost_usd']}"
        )
    lines.append(f"- Pre-annotator `{PREANNOTATOR_MODEL}`; independence of pre-annotator, "
                 "generator and judge families enforced by `leakage.assert_independent_models`.")
    (out / "summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stage", choices=("predict", "judge", "all"), default="all")
    parser.add_argument("--limit", type=int, default=None, help="smoke-run on the first N examples")
    parser.add_argument("--workers", type=int, default=6)
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="write artifacts here instead of reports/ (used to verify without overwriting)",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="reproduce from cache only: a cache miss is a failure, no API call is made",
    )
    parser.add_argument("--gold", choices=golden_paths.VERSIONS, default="v1",
                        help="golden-set version (v1 = evaluated; v2 = corrected PII masking)")
    parser.add_argument("--masker", choices=sorted(MASKERS), default="v1",
                        help="PII masker applied by the agent (v1 = evaluated; v2 = corrected)")
    parser.add_argument("--judge-provider", default="openrouter")
    parser.add_argument("--judge-model", default=JUDGE_MODEL)
    parser.add_argument("--judge-price-in", type=float, default=JUDGE_PRICE[0])
    parser.add_argument("--judge-price-out", type=float, default=JUDGE_PRICE[1])
    args = parser.parse_args()

    out = args.out or _out_dir(args.limit)
    out.mkdir(parents=True, exist_ok=True)
    started = time.time()

    if args.stage in ("predict", "all"):
        records, examples, blind = predict(
            args.limit, offline=args.offline, gold_version=args.gold, masker=args.masker
        )
        (out / "predictions.jsonl").write_bytes(
            ("\n".join(json.dumps(r, ensure_ascii=False, default=str) for r in records) + "\n").encode("utf-8")
        )
        generator_usage = [r["usage"] for r in records if r["system"] == "agent_llm" and r["usage"]]
        generator_totals = {
            "requests": sum(1 for u in generator_usage if not u.get("from_cache")),
            "cache_hits": sum(1 for u in generator_usage if u.get("from_cache")),
            "failures": sum(1 for r in records if r["system"] == "agent_llm"
                            and r["reason"] == "generator_failed"),
            "cost_usd": round(sum((u.get("cost_usd") or 0.0) for u in generator_usage
                                  if not u.get("from_cache")), 6),
        }
        disclosure_block = disclosure(examples, blind)
        (out / "run_context.json").write_text(json.dumps({
            "blind_pair_ids": sorted(blind), "generator_totals": generator_totals,
            "disclosure": disclosure_block}, indent=2) + "\n", encoding="utf-8")
    else:
        records = [json.loads(l) for l in (out / "predictions.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
        context = json.loads((out / "run_context.json").read_text(encoding="utf-8"))
        blind, generator_totals = set(context["blind_pair_ids"]), context["generator_totals"]
        disclosure_block = context["disclosure"]

    judged, judge_summary = None, None
    if args.stage in ("judge", "all"):
        judged, judge_summary = judge(
            records,
            args.workers,
            judge_provider=args.judge_provider,
            judge_model=args.judge_model,
            judge_price=(args.judge_price_in, args.judge_price_out),
            offline=args.offline,
        )
        (out / "judge.jsonl").write_bytes(
            ("\n".join(json.dumps(j, ensure_ascii=False) for j in judged) + "\n").encode("utf-8")
        )

    metrics = compute_metrics(records, blind, judged)
    (out / "metrics.json").write_text(json.dumps({
        "DISCLOSURE": disclosure_block,
        "provenance": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "git_sha": _git_sha(), "taxonomy_version": TAXONOMY.version,
            "taxonomy_hash": TAXONOMY.frozen_hash, "seed": SEED,
            "limit": args.limit, "generator_model": GENERATOR_MODEL,
            "generator_prompt_version": STRUCTURED_PROMPT_VERSION,
            "judge_model": judge_summary["model"] if judge_summary else None,
            "judge_provider": judge_summary["provider"] if judge_summary else None,
            "judge_prompt_version": JUDGE_PROMPT_VERSION,
            "preannotator_model": PREANNOTATOR_MODEL, "corpus": "full train split",
            "bootstrap_resamples": 2000, "elapsed_seconds": round(time.time() - started, 1),
        },
        "generator_totals": generator_totals,
        "judge_summary": judge_summary,
        "metrics": metrics,
    }, indent=2, ensure_ascii=False, default=str) + "\n", encoding="utf-8")
    write_summary(out, metrics, disclosure_block, generator_totals, judge_summary)
    print(f"\nWrote {out}")
    for path in sorted(out.iterdir()):
        print(f"  {path.name}")


if __name__ == "__main__":
    main()
